<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
	'WPV_WPML_Shortcodes_Dialog' => dirname( __FILE__ ) . '/controllers/compatibility/wpml/wpv_wpml_shortcodes_dialog.php',
	'WPV_WPML_Shortcodes_Translation' => dirname( __FILE__ ) . '/controllers/compatibility/wpml/wpv_wpml_shortcodes_translation.php',
	'WPV_WPML_Integration' => dirname( __FILE__ ) . '/controllers/compatibility/wpml/wpv_wpml.php',
	'WPV_WPML_Integration_Embedded' => dirname( __FILE__ ) . '/controllers/compatibility/wpml/wpv_wpml_embedded.php',
	'WPV_Controller_Admin_Help' => dirname( __FILE__ ) . '/controllers/admin/help.php',
	'WPV_Page_Slug' => dirname( __FILE__ ) . '/controllers/page_slugs.php',
	'WPV_Renderer' => dirname( __FILE__ ) . '/controllers/renderer.php',
	'WPV_Main' => dirname( __FILE__ ) . '/controllers/main.php',
);
